# Generated by Django 4.0.3 on 2022-03-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('frequency', models.PositiveIntegerField(verbose_name='Frecuencia')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('measurement_unit', models.CharField(choices=[('ml', 'Mililitro'), ('l', 'Litro'), ('mg', 'Miligramo'), ('g', 'Gramo'), ('kg', 'Kilogramo'), ('u', 'Unidad')], default='g', max_length=2, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tags', models.CharField(choices=[('OM', 'Omnívoro'), ('VT', 'Vegetariano'), ('VG', 'Vegano')], default='OM', max_length=2, verbose_name='Etiquetas')),
                ('day_time', models.CharField(choices=[('LN', 'Almuerzo'), ('DN', 'Cena'), ('DL', 'Almuerzo/Cena')], default='BR', max_length=2, verbose_name='Momento del día')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('cooking_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo de cocción')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='schedule.ingredient', verbose_name='Ingrediente')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.meal', verbose_name='Comida')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('LN', 'Almuerzo'), ('DN', 'Cena')], default='LN', max_length=2, verbose_name='Almuerzo/Cena')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_eaten', models.BooleanField(default=False, verbose_name='Consumida')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.meal', verbose_name='Comida')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'unique_together': {('date', 'meal_time')},
            },
        ),
    ]
