# Generated by Django 3.2.9 on 2021-11-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cooking_time', models.CharField(max_length=10, verbose_name='Tiempo de cocción')),
                ('tags', models.CharField(choices=[('VG', 'Vegano'), ('VT', 'Vegetariano'), ('OM', 'Omnívoro'), ('CL', 'Celíaco')], default='', max_length=2, verbose_name='Etiquetas')),
                ('day_time', models.CharField(choices=[('LN', 'Almuerzo'), ('DN', 'Cena'), ('DL', 'Almuerzo/Cena')], default='BR', max_length=2, verbose_name='Momento del día')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingredients', to='schedule.ingredient', verbose_name='Ingrediente')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.meal', verbose_name='Comida')),
            ],
        ),
    ]
