# Generated by Django 3.2.9 on 2021-12-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('ml', 'Mililitro'), ('l', 'Litro'), ('mg', 'Miligramo'), ('g', 'Gramo'), ('kg', 'Kilogramo'), ('u', 'Unidad')], default='g', max_length=2, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.CharField(choices=[('VG', 'Vegano'), ('VT', 'Vegetariano'), ('OM', 'Omnívoro')], default='', max_length=2, verbose_name='Etiquetas'),
        ),
    ]
