# Generated by Django 4.0.3 on 2022-03-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_schedule_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('date', '-meal_time'), 'verbose_name': 'Menú', 'verbose_name_plural': 'Menús'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='scheduler.meal', verbose_name='Comida'),
        ),
    ]
